name: 'gitStream repo agent'
description: 'Public GitHub action for gitStream Continuous Merge'

inputs:
  full_repository:
    description: 'Path of full Repository'
    required: true
  head_ref:
    description: 'Head Branch Ref to checkout to'
    required: true
  base_ref:
    description: 'Base Branch Ref to checkout to'
    required: true
  client_payload:
    description: 'The client payload'
    required: true
  installation_id:
    description: 'The github app installation id'
    required: false
  resolver_url:
    description: 'Resolver url to send results to'
    required: true
  resolver_token:
    description: 'Optional token for resolver'
    required: false
  debug_mode:
    description: 'Run parser in debug mode'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 20.12.2

    - name: Create GitStream folder
      shell: bash
      run: |
        rm -rf gitstream && rm -rf code && mkdir gitstream
        cd gitstream && mkdir repo

    - name: Checkout base branch
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ inputs.full_repository }}
        ref: ${{ inputs.base_ref }}
        path: gitstream/repo/
        token: ${{ fromJSON(fromJSON(inputs.client_payload)).githubToken || github.token }}

    - name: Escape single quotes
      id: safe-strings
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        BASE_REF_ARG: ${{ inputs.base_ref }}
        HEAD_REF_ARG: ${{ inputs.head_ref }}
        PAYLOAD_ARG: ${{ inputs.client_payload }}
        URL_ARG: ${{ fromJSON(fromJSON(inputs.client_payload)).headHttpUrl || fromJSON(fromJSON(inputs.client_payload)).repoUrl }}
      with:
        script: |
          try {
            function convertToSafeString(input) {
              return (input || '').replace(/['`]/g, "\\$&");
            };
            function escapeApostrophe(input) {
              return (input || '').replace(/'/g, "\\'");
            };
            const base_ref = escapeApostrophe(process.env.BASE_REF_ARG);
            const head_ref = escapeApostrophe(process.env.HEAD_REF_ARG);
            const url = convertToSafeString(process.env.URL_ARG);
            const client_payload = convertToSafeString(process.env.PAYLOAD_ARG);
            core.setOutput('base_ref', base_ref);
            core.setOutput('head_ref', head_ref);
            core.setOutput('url', url);
            core.setOutput('client_payload', client_payload);
          } catch (err) {
            core.error(`Failed producing safe string: ${err}`);
            process.exit(1);
          }

    - name: Checkout Pull Request branches history
      shell: bash
      run: |
        cd gitstream && cd repo
        git config checkout.defaultRemote origin
        git fetch --shallow-since="6 months ago" origin $'${{ steps.safe-strings.outputs.base_ref }}'
        git remote add upstream $'${{ steps.safe-strings.outputs.url }}'
        git fetch --shallow-since="6 months ago" upstream $'${{ steps.safe-strings.outputs.head_ref }}' || echo "::warning::Failed to fetch head branch. The branch may have been deleted."
        git checkout -b $'upstream/${{ steps.safe-strings.outputs.head_ref}}' $'upstream/${{ steps.safe-strings.outputs.head_ref}}' || true
        git checkout $'${{ steps.safe-strings.outputs.base_ref }}' || true
        git checkout $'${{ steps.safe-strings.outputs.head_ref }}' || true

    - name: Create cm folder
      shell: bash
      run: cd gitstream && mkdir cm

    - name: Checkout cm repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      if: ${{ fromJSON(fromJSON(inputs.client_payload)).hasCmRepo == true }}
      with:
        repository: '${{ fromJSON(fromJSON(inputs.client_payload)).owner }}/${{ fromJSON(fromJSON(inputs.client_payload)).cmRepo }}'
        ref: ${{ fromJSON(fromJSON(inputs.client_payload)).cmRepoRef }}
        path: gitstream/cm/
        fetch-depth: 1

    - name: Checkout cm org
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      if: ${{ fromJSON(fromJSON(inputs.client_payload)).hasCmOrg == true }}
      with:
        repository: 'cm/cm'
        ref: ${{ fromJSON(fromJSON(inputs.client_payload)).cmOrgRef }}
        path: gitstream/cm/
        fetch-depth: 1

    - name: Volume folder
      shell: bash
      run: mv gitstream code

    - name: Run RulesEngine
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        NODE_PATH: ${{ github.action_path }}/dist/node_modules
        HEAD_REF: ${{ steps.safe-strings.outputs.head_ref }}
        BASE_REF: ${{ steps.safe-strings.outputs.base_ref }}
        CLIENT_PAYLOAD: ${{ steps.safe-strings.outputs.client_payload }}
        RULES_RESOLVER_URL: ${{ inputs.resolver_url }}
        RULES_RESOLVER_TOKEN: ${{ inputs.resolver_token }}
        DEBUG_MODE: ${{ inputs.debug_mode }}
        ENABLE_DEBUG_ARTIFACTS: ${{ env.ENABLE_DEBUG_ARTIFACTS }}
        RUN_ID: ${{ github.run_id }}

    - name: Upload artifacts
      if: ${{ env.ENABLE_DEBUG_ARTIFACTS == 'true' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        retention-days: 7
        name: output
        path: code/output
