name: 'gitStream repo agent'
description: 'Public GitHub action for gitStream Continuous Merge'
inputs:
  full_repository:
    description: 'Path of full Repository'
    required: true
  head_ref:
    description: 'Head Branch Ref to checkout to'
    required: true
  base_ref:
    description: 'Base Branch Ref to checkout to'
    required: true
  client_payload:
    description: 'The client payload'
    required: true
  installation_id:
    description: 'The github app installation id'
    required: false
  resolver_url:
    description: 'Resolver url to send results to'
    required: true
  resolver_token:
    description: 'Optional token for resolver'
    required: false
  debug_mode:
    description: 'Run parser in debug mode'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Set start time
      id: start
      run: echo "timestamp=$EPOCHSECONDS" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create GitStream folder
      id: create-gitstream-folder
      shell: bash
      run: |
        mkdir gitstream
        cd gitstream
        mkdir repo

    - name: Cache gitstream results
      id: cache-gitstream-results
      uses: actions/cache@v3
      with:
        path: gitstream/cache.json
        key: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).headSha }}-gitstream-cache

    - name: Checkout base branch
      uses: actions/checkout@v3
      if: ${{ steps.cache-gitstream-results.outputs.cache-hit != 'true' }}
      with:
        repository: ${{ inputs.full_repository }}
        ref: ${{ github.event.inputs.base_ref }}
        path: 'gitstream/repo/'
        token: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).githubToken || github.token }}

    - name: Escape single quotes
      id: escape-quotes
      uses: actions/github-script@v3
      with:
        base_ref_arg: ${{ github.event.inputs.base_ref }}
        head_ref_arg: ${{ github.event.inputs.head_ref }}
        url_arg: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).headHttpUrl || fromJSON(fromJSON(github.event.inputs.client_payload)).repoUrl }}
        script: |
          function escapeSingleQuoteChars(input) {
            return (input || '').replace(/'/g, "\\'");
          };
          const base_ref = escapeSingleQuoteChars(core.getInput('base_ref_arg'));
          const head_ref = escapeSingleQuoteChars(core.getInput('head_ref_arg'));
          const url = escapeSingleQuoteChars(core.getInput('url_arg'));
          core.setOutput('base_ref', base_ref);
          core.setOutput('head_ref', head_ref);
          core.setOutput('url', url);
          core.info(`base_ref ${base_ref}`)
          core.info(`head_ref ${head_ref}`)
          core.info(`url ${url}`)
    - if: ${{ steps.cache-gitstream-results.outputs.cache-hit != 'true' }}
      run: |
        all=2147483647
        cd gitstream
        cd repo
        echo "bash_ref ${{ steps.escape-quotes.outputs.base_ref }}"
        echo "head_ref ${{ steps.escape-quotes.outputs.head_ref}}"
        echo "url ${{ steps.escape-quotes.outputs.url }}"
        git fetch --deepen=$all origin $'${{ steps.escape-quotes.outputs.base_ref }}'
        git remote add upstream $'${{ steps.escape-quotes.outputs.url }}'
        git fetch --deepen=$all upstream $'${{ steps.escape-quotes.outputs.head_ref }}'
        git checkout -b $'upstream/${{ steps.escape-quotes.outputs.head_ref}}' $'upstream/${{ steps.escape-quotes.outputs.head_ref}}'
      shell: bash

    - name: Create cm folder
      id: create-cm-folder
      shell: bash
      run: |
        cd gitstream
        mkdir cm
    - name: Checkout cm repo
      uses: actions/checkout@v3
      if: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).hasCmRepo == true }}
      with:
        repository: '${{ fromJSON(fromJSON(github.event.inputs.client_payload)).owner }}/${{ fromJSON(fromJSON(github.event.inputs.client_payload)).cmRepo }}'
        ref: ${{ fromJSON(fromJSON(github.event.inputs.client_payload)).cmRepoRef }}
        path: 'gitstream/cm/'
    - name: Run The Action
      id: gitstream-action
      if: always()
      run: |
        SECONDS=0
        env_file=env.user
        touch $env_file
        for var in $(env | cut -d "=" -f 1); do
          value="${!var}"
          echo "$var=$value" >> "$env_file"
        done
        docker pull gitstream/rules-engine:eladushTag
        echo "docker-pull-duration=$SECONDS" >> $GITHUB_OUTPUT
        SECONDS=0
        docker run --env-file $env_file -v $(pwd)/gitstream:/code -e USE_CACHE=${{ steps.cache-gitstream-results.outputs.cache-hit }} -e HEAD_REF=$'upstream/${{ steps.escape-quotes.outputs.head_ref }}' -e BASE_REF=$'${{ steps.escape-quotes.outputs.base_ref }}' -e CLIENT_PAYLOAD=${{ github.event.inputs.client_payload }} -e RULES_RESOLVER_URL=${{ github.event.inputs.resolver_url }} -e RULES_RESOLVER_TOKEN=${{ github.event.inputs.resolver_token }} -e DEBUG_MODE=${{ github.event.inputs.debug_mode }} gitstream/rules-engine:eladushTag
        echo "docker-run-duration=$SECONDS" >> $GITHUB_OUTPUT
        echo "action-run-duration=$(($EPOCHSECONDS - ${{ steps.start.outputs.timestamp }}))" >> $GITHUB_OUTPUT
      shell: bash
