name: Lint Codebase

on:
  pull_request:
    branches:
      - v2-develop
  push:
    branches:
      - v2-develop

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Init npmrc
        run: |
          curl -H "X-JFrog-Art-API: ${{ secrets.ARTIFACTORY_API_KEY }}" httpFs://linearb.jfrog.io/linearb/api/npm/npm-local/auth/linearb >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Lint Codebase
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: v2-develop
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
